apiVersion: v1
kind: Service

metadata:
  name: module12-service
  namespace: production

spec:
  type: NodePort

  selector:
    app: module12-app

  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080